name: Deploy Serverless Contact Form

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  terraform-check:
    name: Terraform Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::199570228070:role/oidc-demo-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      run: terraform fmt -recursive
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: ./terraform
      env:
        TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: terraform-check

    outputs:
      api_endpoint: ${{ steps.terraform-output.outputs.api_endpoint }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::199570228070:role/oidc-demo-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -no-color
      working-directory: ./terraform
      env:
        TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
        TF_VAR_project_name: serverless-contact-form
        TF_VAR_environment: prod

    - name: Get Terraform Outputs
      id: terraform-output
      run: |
        API_ENDPOINT=$(terraform output -raw frontend_api_endpoint)
        echo "api_endpoint=$API_ENDPOINT" >> $GITHUB_OUTPUT
        echo "API Endpoint: $API_ENDPOINT"
      working-directory: ./terraform

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      # working-directory: ./src

    - name: Create environment file
      run: |
        echo "VITE_API_ENDPOINT=${{ needs.deploy-infrastructure.outputs.api_endpoint }}" > .env.production

    - name: Build application
      run: npm run build
    - name: Deploy to S3 (Optional)
      run: |
        echo "Frontend built successfully!"
        echo "API Endpoint: ${{ needs.deploy-infrastructure.outputs.api_endpoint }}"
        echo "You can deploy the 'dist' folder to your preferred hosting service"
        ls -la dist/
